<a href="https://colab.research.google.com/github/Kirithika-M/Machine-Learning-Lab/blob/main/ML_lab_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Experiment 3 : Linear Regression

#### Step 1 : Import all the libraries and read the dataset

In [9]:
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error, mean_squared_error
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [7]:
dataset = pd.read_csv("/content/student_scores (2).csv")
print(f"Head: \n{dataset.head()}")
print()
print(f"Tail: \n{dataset.tail()}")

Head: 
   Hours  Scores
0    2.5      21
1    5.1      47
2    3.2      27
3    8.5      75
4    3.5      30

Tail: 
    Hours  Scores
20    2.7      30
21    4.8      54
22    3.8      35
23    6.9      76
24    7.8      86


#### Step 2 : Analyze the data and do preprocessing if required

In [8]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Hours   25 non-null     float64
 1   Scores  25 non-null     int64  
dtypes: float64(1), int64(1)
memory usage: 532.0 bytes


#### Step 3  : Analyze the input and output features

In [13]:
# Assigning hours to X & scores to Y
X = dataset.iloc[:,:-1].values
print(X)

Y = dataset.iloc[:,-1].values
print(Y)

[[2.5]
 [5.1]
 [3.2]
 [8.5]
 [3.5]
 [1.5]
 [9.2]
 [5.5]
 [8.3]
 [2.7]
 [7.7]
 [5.9]
 [4.5]
 [3.3]
 [1.1]
 [8.9]
 [2.5]
 [1.9]
 [6.1]
 [7.4]
 [2.7]
 [4.8]
 [3.8]
 [6.9]
 [7.8]]
[21 47 27 75 30 20 88 60 81 25 85 62 41 42 17 95 30 24 67 69 30 54 35 76
 86]


#### Step 4 : Split your data into training data and testing data

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=1/3, random_state=0)

print(f"X_train : \n{X_train}")
print()

print(f"X_test : \n{X_test}")
print()

print(f"Y_train: \n{Y_train}")
print()

print(f"Y_test : \n{Y_test}")
print()

X_train : 
[[1.1]
 [5.1]
 [7.7]
 [3.3]
 [8.3]
 [9.2]
 [6.1]
 [3.5]
 [2.7]
 [5.5]
 [2.7]
 [8.5]
 [2.5]
 [4.8]
 [8.9]
 [4.5]]

X_test : 
[[1.5]
 [3.2]
 [7.4]
 [2.5]
 [5.9]
 [3.8]
 [1.9]
 [7.8]
 [6.9]]

Y_train: 
[17 47 85 42 81 88 67 30 25 60 30 75 21 54 95 41]

Y_test : 
[20 27 69 30 62 35 24 86 76]



In [17]:
print(X_train.shape)

(16, 1)


In [18]:
print(X_test.shape)

(9, 1)


In [19]:
print(Y_train.shape)

(16,)


In [20]:
print(Y_test.shape)

(9,)


#### Step 5 : Use appropriate algorithm for training

In [21]:
from sklearn.linear_model import LinearRegression

reg = LinearRegression()    # Supervised Machine Learning
reg.fit(X_train, Y_train)   # fit() is the training command

[17.04289179 33.51695377 74.21757747 26.73351648 59.68164043 39.33132858
 20.91914167 78.09382734 69.37226512]
[20 27 69 30 62 35 24 86 76]


#### Step 6 : Predict using the developed model

In [24]:
# Prediction
Y_pred = reg.predict(X_test)

print(Y_pred)
print(Y_test)

[17.04289179 33.51695377 74.21757747 26.73351648 59.68164043 39.33132858
 20.91914167 78.09382734 69.37226512]
[20 27 69 30 62 35 24 86 76]


#### Step 7 : Evaluate the performance metrics

In [23]:
mse = mean_squared_error(Y_test, Y_pred)
print("MSE = ",mse)

mae = mean_absolute_error(Y_test, Y_pred)
print("MAE = ",mae)

rmse = np.sqrt(mse)
print("RMSE = ",rmse)

MSE =  25.463280738222593
MAE =  4.691397441397446
RMSE =  5.046115410711748
